"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = C:\Users\USER\Desktop\장고튜토리얼\mysite

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@du4@$wx@=sd0^p4z9)_x-z@tj3m)z8t2jrrq&z_*r_3et9yvw"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # 나중에 배포할 때는 False로 해주기

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["*"] # 수정


# Application definition
# python manage.py migrate를 하면 INSTALLED_APPS 가 (admin, auth, contenttypes 이런 앱들이) 변경되면 적용이 되는 것이다.
# DB만들고 나서 migrate해줄 때는 makemigrate 먼저 해야한다. (admin, session 이런 건 기본앱이라 migrate만 해도 되는데 내가 직접 새로만든 DB나 앱들은 makemigrations 해줘야 함.
INSTALLED_APPS = [ # 프로그램
    "pybo.apps.PyboConfig",# DB사용을 위한 추가 - pybo도 app 취급, pybo의 apps.py에서 가져옴
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [ # 소프트웨어
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware", ## 중요! 
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls" # urls.py 파일이 메인이다.

TEMPLATES = [ # HTML 파일이 모인 디렉토리에 대한 설정
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'], # 추가 - mysite밑에 templates 디렉토리에 있는 html,css,js 등을 봐라
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "ko-kr" # 언어-국가


# TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Seoul" # 지역


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/" # javascript, css, 이미지가 오는 디렉토리
STATICFILES_DIRS = [BASE_DIR / 'static',] # 추가 , 꾸미기 디렉토리

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
