# Generated by Django 4.2.2 on 2023-06-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="create_date", new_name="createdate",
        ),
    ]
