# Generated by Django 4.2.2 on 2023-06-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0002_rename_create_date_question_createdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="createdate", new_name="create_date",
        ),
    ]
