# Generated by Django 4.2.2 on 2023-06-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0003_rename_createdate_question_create_date"),
    ]

    operations = [
        migrations.DeleteModel(name="Answer",),
        migrations.DeleteModel(name="Question",),
    ]
